alias: Lock Car on Away
description: ""
triggers:
  - alias: Phone - Disconnected
    trigger: state
    entity_id:
      - binary_sensor.[PHONE_CONNECTED_SENSOR]
    from: "on"
    to: "off"
    for:
      hours: 0
      minutes: 0
      seconds: 0
conditions:
  - condition: state
    entity_id: sensor.[PHONE_WIFI_BSSID_SENSOR]
    state: [CAR MAC ADDRESS]
    alias: Car BSSID
actions:
  - alias: Wait for away (max 6:45 minutes)
    wait_for_trigger:
      - alias: Phone - Away
        entity_id:
          - sensor.[PHONE_WIFI_BSSID_SENSOR]
        from: [CAR MAC ADDRESS]
        trigger: state
    timeout:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
    continue_on_timeout: false
  - device_id: [LOCK_DEVICE_ID]
    domain: lock
    entity_id: [CAR_DOOR_LOCK_ENTITY]
    type: lock
    alias: Car Doors - Lock
mode: restart
